/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Auditorias': RouteRecordInfo<'/Auditorias', '/Auditorias', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/Materiais': RouteRecordInfo<'/Materiais', '/Materiais', Record<never, never>, Record<never, never>>,
    '/Monitoramento': RouteRecordInfo<'/Monitoramento', '/Monitoramento', Record<never, never>, Record<never, never>>,
    '/Utilizadores': RouteRecordInfo<'/Utilizadores', '/Utilizadores', Record<never, never>, Record<never, never>>,
  }
}
